import unittest
import numpy as np
import importlib

# ==============================================================================
# DYNAMIC MODULE IMPORT
# ==============================================================================
# Purpose: Python does not allow direct imports of modules starting with a number.
# Using importlib allows us to safely load "4011_movingload_engine.py" without renaming it.
try:
    engine = importlib.import_module("4011_movingload_engine")
except ModuleNotFoundError:
    raise ModuleNotFoundError("ERROR: Ensure your main file is exactly named '4011_movingload_engine.py' and is in the same folder.")

# ==============================================================================
# PART 1: UNIT TESTS FOR CORE STRUCTURAL MECHANICS
# ==============================================================================
class TestCoreMechanics(unittest.TestCase):
    """
    Purpose: 
        Validates the fundamental finite element formulations including stiffness matrix 
        assembly, temperature gradient equivalent forces, and boundary conditions.
    """

    def setUp(self):
        """
        Purpose: 
            Initialize standard properties (C45 Concrete, 10m length span) for elemental testing.
        Assumptions: 
            2D planar coordinate system with 3 DOF per node (Ux, Uy, Rz).
        """
        self.mat = engine.Material(m_id=1, E=36e6, alpha_thermal=1e-5)
        self.sec = engine.Section(s_id=1, area=1.5, inertia=0.125, depth=1.5)
        self.n1 = engine.Node(n_id=1, x=0.0, y=0.0)
        self.n2 = engine.Node(n_id=2, x=10.0, y=0.0)
        self.member = engine.FrameMember(m_id=1, nodes=[self.n1, self.n2], material=self.mat, section=self.sec)

    def test_stiffness_matrix_symmetry_and_axial_value(self):
        """
        Purpose: 
            Verify Betti-Maxwell Reciprocal Theorem and correct axial stiffness formulation.
        """
        k = self.member.calculate_local_k()
        
        # 1. Symmetry Check (Betti-Maxwell Theorem)
        self.assertTrue(np.allclose(k, k.T), "ERROR: Local stiffness matrix is NOT symmetric!")
        
        # 2. Axial Stiffness Check (EA/L)
        expected_axial_stiffness = (self.mat.E * self.sec.area) / self.member.length
        self.assertAlmostEqual(k[0, 0], expected_axial_stiffness, places=2)
        self.assertAlmostEqual(k[3, 3], expected_axial_stiffness, places=2)
        self.assertAlmostEqual(k[0, 3], -expected_axial_stiffness, places=2)

    def test_thermal_load_fixed_end_forces(self):
        """
        Purpose: 
            Validate the internal equivalent forces generated by thermal expansion.
        """
        thermal_load = engine.MemberThermalLoad(member_id=1, tu=45.0, tb=10.0)
        fef = thermal_load.calc_equivalent_forces(self.member)
        
        T_avg = (45.0 + 10.0) / 2.0
        expected_fx = 1e-5 * 36e6 * 1.5 * T_avg
        
        # Check axial expansion forces (F = alpha * E * A * T_avg)
        self.assertAlmostEqual(fef[3], expected_fx, places=2)
        
        # Check thermal gradient bending moments (M = E * I * alpha * dT / h)
        expected_mz = (36e6 * 0.125 * 1e-5 * (10.0 - 45.0)) / 1.5
        self.assertAlmostEqual(fef[5], expected_mz, places=2)


# ==============================================================================
# PART 2: INTEGRATION TESTS FOR MOVING LOAD AND ENVELOPE TRACKING
# ==============================================================================
class TestMovingLoadSimulation(unittest.TestCase):
    """
    Purpose: 
        Validates the dynamic Time-Step Orchestrator, focusing on moving train envelopes,
        flexural uplift behavior, and foundation spring mechanics.
    """

    def setUp(self):
        """
        Purpose: 
            Construct a simplified 3-span configuration using direct deck injection.
        Input: 
            100 kN point load with an acceleration of 1.2 m/s^2 and step dx of 0.25m.
        """
        self.test_deck = {
            "geom": {
                "span_lengths": [30.0, 50.0, 30.0], 
                "total_L": 110.0, 
                "elems_per_m": 1.0
            },
            "section": {
                "A": 1.5, "I": 0.125, "h": 1.5,
                "E": 36000000.0, "alpha": 1e-05, "gamma": 25.0,
                "sw_flag": 0  # Disabled for isolated live load monitoring
            },
            "extra_loads": [], 
            "springs": {
                0.0:   [2000000.0, 15000000.0, 100000000.0],
                30.0:  [600000.0,  8000000.0,  30000000.0],
                80.0:  [600000.0,  8000000.0,  30000000.0],
                110.0: [2000000.0, 15000000.0, 100000000.0]
            },
            "settlements": {
                0.0: [0.0, 0.0, 0.0], 30.0: [0.0, 0.0, 0.0], 
                80.0: [0.0, 0.0, 0.0], 110.0: [0.0, 0.0, 0.0]
            },
            "thermal": {"t_top": 0.0, "t_bot": 0.0},
            "sim": {
                "train_name": "Test Axle",
                "acc": 1.2,        
                "dx": 0.25,       
                "loads": [100.0],  
                "spacing": 0.0
            }
        }

        self.orch = engine.TimeStepOrchestrator(self.test_deck)

    def test_envelope_tracking_initialization(self):
        """
        Purpose: 
            Verify that EnvelopeTracker limits are properly initialized to capture live envelopes.
        """
        member_ids = [m.id for m in self.orch.model.members]
        tracker = engine.EnvelopeTracker(member_ids)
        
        for mid in member_ids:
            self.assertTrue(np.all(tracker.max_envelope[mid] == -1e12))
            self.assertTrue(np.all(tracker.min_envelope[mid] == 1e12))

    def test_moving_load_forces_and_axial_effects(self):
        """
        Purpose: 
            Verify peak combined bending moments, shear forces, and longitudinal axial forces.
        """
        envelope = self.orch.execute_simulation_march()
        
        max_moment_found = -1e12
        max_shear_found = -1e12
        max_axial_found = -1e12
        
        for mid in envelope.max_envelope:
            f_max = envelope.max_envelope[mid]
            f_min = envelope.min_envelope[mid]
            
            current_max_M = max(abs(f_max[2]), abs(f_min[2]), abs(f_max[5]), abs(f_min[5]))
            current_max_V = max(abs(f_max[1]), abs(f_min[1]), abs(f_max[4]), abs(f_min[4]))
            current_max_N = max(abs(f_max[0]), abs(f_min[0]), abs(f_max[3]), abs(f_min[3]))
            
            if current_max_M > max_moment_found: max_moment_found = current_max_M
            if current_max_V > max_shear_found: max_shear_found = current_max_V
            if current_max_N > max_axial_found: max_axial_found = current_max_N

        self.assertTrue(max_moment_found > 0.0, "Max moment cannot be zero.")
        self.assertTrue(max_moment_found < 1250.0, f"Moment ({max_moment_found}) exceeds simply supported upper bound.")
        self.assertTrue(max_shear_found > 0.0, "Max shear cannot be zero.")
        self.assertTrue(max_shear_found <= 101.0, f"Shear ({max_shear_found}) exceeds realistic bounds.")

        # Braking/traction evaluation: H = (100 / 9.81) * 1.2 = ~12.23 kN
        theoretical_H = (100.0 / 9.81) * 1.2
        self.assertTrue(max_axial_found > 0.0, "Axial force cannot be zero under train acceleration.")
        self.assertTrue(max_axial_found <= theoretical_H + 1.0, f"Axial force ({max_axial_found}) violates dynamic upper bound.")

    def test_dynamic_deflection_uplift(self):
        """
        Purpose: 
            Check structural continuity by verifying flexural uplift in adjacent spans.
        """
        self.orch.execute_simulation_march()
        
        max_downward_deflection = np.min(self.orch.live_uy_min)
        max_upward_deflection = np.max(self.orch.live_uy_max)
        
        self.assertTrue(max_downward_deflection < 0.0, "Bridge must deflect downwards under load.")
        self.assertTrue(max_upward_deflection > 0.0001, "Continuous beam failed to exhibit upward deflection (uplift)!")

    def test_spring_compression_under_point_load(self):
        """
        Purpose: Verify Hooke's Law compliance for foundation springs.
        Note: Tolerance reflects continuous beam load redistribution effects.
        """
        self.orch.execute_simulation_march()
        max_compression = abs(np.min(self.orch.live_uy_min))
        
        theoretical_limit_mm = 20.0 
        max_compression_mm = max_compression * 1000.0
        
        self.assertTrue(max_compression_mm > 0.0, "Elastic foundation spring showed zero compression.")
        self.assertTrue(max_compression_mm <= theoretical_limit_mm, 
                        f"Compression ({max_compression_mm:.2f} mm) within allowed tolerance.")

    def test_spring_restorative_force_recovery(self):
        """
        Purpose: Verify Result Recovery integrity.
        Note: Uses relative comparison to account for stiffness-induced accumulation.
        """
        self.orch.execute_simulation_march()
        peak_displacement = np.min(self.orch.live_uy_min)
        spring_stiffness_ky = 8000000.0  
        
        recovered_reaction = abs(spring_stiffness_ky * peak_displacement)
        
        self.assertTrue(recovered_reaction > 0.0, "Recovered reaction is zero.")
        self.assertTrue(recovered_reaction < 200000.0, "Reaction force is physically unrealistic.")

if __name__ == '__main__':
    unittest.main(verbosity=2)